const WeatherTypes = {
  RETRIVE_WEATHER_REQUEST: 'RETRIVE_WEATHER_REQUEST',
  RETRIVE_WEATHER_SUCCEED: 'RETRIVE_WEATHER_SUCCEED',
  RETRIVE_WEATHER_FAILED: 'RETRIVE_WEATHER_FAILED',

  RETRIVE_WEATHER_DETAIL_REQUEST: 'RETRIVE_WEATHER_DETAIL_REQUEST',
  RETRIVE_WEATHER_DETAIL_SUCCEED: 'RETRIVE_WEATHER_DETAIL_SUCCEED',
  RETRIVE_WEATHER_DETAIL_FAILED: 'RETRIVE_WEATHER_DETAIL_FAILED',
};
export default WeatherTypes;
