import {Dimensions, Platform} from 'react-native';

const {width, height} = Dimensions.get('window');

// Used via Metrics.baseMargin
const metrics = {
  halfLeft: '50%',
  halfTop: '50%',
  iconMinWidthSmall: 50,
  iconMinWidthSmallX: 65,
  iconMinWidthMedium: 80,
  heightMedium: 60,
  heightMediumX: 130,
  heightLarge: 150,
  margin_minus: -70,
  marginTiny: 2,
  marginTinyX: 3,
  marginSmall: 4,
  marginSmallX: 6,
  marginMedium: 8,
  marginMediumX: 10,
  marginMediumX2: 12,
  marginMediumX3: 16,
  marginMediumX4: 20,
  marginLarge: 24,
  marginLargeX2: 30,
  marginLargeX3: 35,
  marginLargeX4: 50,
  marginLargeX5: 60,
  marginLargeX6: 70,
  paddingTiny: 2,
  paddingTinyX: 4,
  paddingSmall: 6,
  paddingSmallX: 10,
  paddingMedium: 12,
  paddingMediumX: 20,
  paddingMediumXX: 25,
  paddingMediumXXX: 30,
  paddingLarge: 35,
  padding_FL_Bottom: 120,
  doubleSection: 50,
  searchBarHeight: 30,
  viewHeight: 32,
  viewHeightSmall: 15,
  screenWidth: width < height ? width : height,
  screenHeight: width < height ? height : width,
  screenRatio: width * height,
  tabBarHeight: (width < height ? height : width) / 12,
  navBarHeight: Platform.OS === 'ios' ? 64 : 54,
  androidStatusBarHeight: 25,
  radiusTiny: 5,
  radiusSmall: 10,
  radiusSmallX: 20,
  radiusMedium: 30,
  radiumLarge: 50,
  radiumXLarge: 60,
  radiumFull: 100,
  buttonSmall: 20,
  buttonMedium: 30,
  buttonMediumX: 40,
  buttonLarge: 50,
  cardItemHeight: 40,
  cardItemHeightX: 180,
  headerBarHeight: 55,
  seperatorWidth: 1,
  margin_160: 160,
  dropdown_120: 120,
  icons: {
    extiny: 14,
    tiny: 18,
    exsmall: 20,
    ssmall: 23,
    small: 25,
    smallX: 28,
    medium: 30,
    mediumX: 40,
    large: 45,
    xl: 50,
    xxl: 70,
  },
  images: {
    small: 20,
    smallX: 25,
    smallXX: 30,
    smallXXX: 35,
    medium: 40,
    large: 60,
    largeL: 65,
    largeX: 80,
    largeXL: 90,
    largeXX: 110,
    smallLogo: 130,
    smallLogoHeight: 70,
    logo: 200,
    profile: 100,
  },
  fonts: {
    title: 20,
    large: 50,
  },
};

export default metrics;
