const HomeTypes = {
  RETRIVE_WEATHER_REQUEST: 'RETRIVE_WEATHER_REQUEST',
  RETRIVE_WEATHER_SUCCEED: 'RETRIVE_WEATHER_SUCCEED',
  RETRIVE_WEATHER_FAILED: 'RETRIVE_WEATHER_FAILED',
};
export default HomeTypes;
